name: mindmosaic
version: 1.0.0+1
description: A clean, calming micro-mental-health and wellness check app.
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.2
  audioplayers: ^6.1.0
  fl_chart: ^0.69.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/icons/